<?php

declare(strict_types=1);

namespace Ntvspa\Big\Booking;

/**
 * Class which returns the class map definition
 */
class ClassMap
{
    /**
     * Returns the mapping between the WSDL Structs and generated Structs' classes
     * This array is sent to the \SoapClient when calling the WS
     *
     * @return string[]
     */
    final public static function get(): array
    {
        return [
            'GetAvailableTrainsRequest'              => '\\Ntvspa\\Big\\Booking\\Structs\\GetAvailableTrainsRequest',
            'GetAvailableTrainsResponse'             => '\\Ntvspa\\Big\\Booking\\Structs\\GetAvailableTrainsResponse',
            'GetAvailableTrainsData'                 => '\\Ntvspa\\Big\\Booking\\Structs\\GetAvailableTrainsData',
            'AgentPromotion'                         => '\\Ntvspa\\Big\\Booking\\Structs\\AgentPromotion',
            'AncillaryService'                       => '\\Ntvspa\\Big\\Booking\\Structs\\AncillaryService',
            'GetUpgradeAvailabilityData'             => '\\Ntvspa\\Big\\Booking\\Structs\\GetUpgradeAvailabilityData',
            'JourneySpecialOperation'                => '\\Ntvspa\\Big\\Booking\\Structs\\JourneySpecialOperation',
            'ArrayOfLeg'                             => '\\Ntvspa\\Big\\Booking\\Arrays\\ArrayOfLeg',
            'Leg'                                    => '\\Ntvspa\\Big\\Booking\\Structs\\Leg',
            'ArrayOfLegSSR'                          => '\\Ntvspa\\Big\\Booking\\Arrays\\ArrayOfLegSSR',
            'LegSSR'                                 => '\\Ntvspa\\Big\\Booking\\Structs\\LegSSR',
            'ArrayOfPassengerSeatPreference'         => '\\Ntvspa\\Big\\Booking\\Arrays\\ArrayOfPassengerSeatPreference',
            'PassengerSeatPreference'                => '\\Ntvspa\\Big\\Booking\\Structs\\PassengerSeatPreference',
            'ArrayOfSegmentSeat'                     => '\\Ntvspa\\Big\\Booking\\Arrays\\ArrayOfSegmentSeat',
            'SegmentSeat'                            => '\\Ntvspa\\Big\\Booking\\Structs\\SegmentSeat',
            'BookingContact'                         => '\\Ntvspa\\Big\\Booking\\Structs\\BookingContact',
            'PassengerInfant'                        => '\\Ntvspa\\Big\\Booking\\Structs\\PassengerInfant',
            'BookingSum'                             => '\\Ntvspa\\Big\\Booking\\Structs\\BookingSum',
            'ArrayOfPassenger'                       => '\\Ntvspa\\Big\\Booking\\Arrays\\ArrayOfPassenger',
            'Passenger'                              => '\\Ntvspa\\Big\\Booking\\Structs\\Passenger',
            'ArrayOfPassengerFee'                    => '\\Ntvspa\\Big\\Booking\\Arrays\\ArrayOfPassengerFee',
            'PassengerFee'                           => '\\Ntvspa\\Big\\Booking\\Structs\\PassengerFee',
            'ArrayOfBookingServiceCharge'            => '\\Ntvspa\\Big\\Booking\\Arrays\\ArrayOfBookingServiceCharge',
            'BookingServiceCharge'                   => '\\Ntvspa\\Big\\Booking\\Structs\\BookingServiceCharge',
            'ArrayOfAvailableSSR'                    => '\\Ntvspa\\Big\\Booking\\Arrays\\ArrayOfAvailableSSR',
            'AvailableSSR'                           => '\\Ntvspa\\Big\\Booking\\Structs\\AvailableSSR',
            'ArrayOfAssignedSSR'                     => '\\Ntvspa\\Big\\Booking\\Arrays\\ArrayOfAssignedSSR',
            'AssignedSSR'                            => '\\Ntvspa\\Big\\Booking\\Structs\\AssignedSSR',
            'ArrayOfPaxSeat'                         => '\\Ntvspa\\Big\\Booking\\Arrays\\ArrayOfPaxSeat',
            'PaxSeat'                                => '\\Ntvspa\\Big\\Booking\\Structs\\PaxSeat',
            'PointOfSale'                            => '\\Ntvspa\\Big\\Booking\\Structs\\PointOfSale',
            'ExtraInfo'                              => '\\Ntvspa\\Big\\Booking\\Structs\\ExtraInfo',
            'ItaloPiuRegistrationRules'              => '\\Ntvspa\\Big\\Booking\\Structs\\ItaloPiuRegistrationRules',
            'FareLockInfoData'                       => '\\Ntvspa\\Big\\Booking\\Structs\\FareLockInfoData',
            'ArrayOfPaymentField'                    => '\\Ntvspa\\Big\\Booking\\Arrays\\ArrayOfPaymentField',
            'PaymentField'                           => '\\Ntvspa\\Big\\Booking\\Structs\\PaymentField',
            'BookingSummary'                         => '\\Ntvspa\\Big\\Booking\\Structs\\BookingSummary',
            'ArrayOfJourney'                         => '\\Ntvspa\\Big\\Booking\\Arrays\\ArrayOfJourney',
            'Journey'                                => '\\Ntvspa\\Big\\Booking\\Structs\\Journey',
            'ArrayOfPaxSSR'                          => '\\Ntvspa\\Big\\Booking\\Arrays\\ArrayOfPaxSSR',
            'PaxSSR'                                 => '\\Ntvspa\\Big\\Booking\\Structs\\PaxSSR',
            'ResponseBase'                           => '\\Ntvspa\\Big\\Booking\\Structs\\ResponseBase',
            'ArrayOfWarning'                         => '\\Ntvspa\\Big\\Booking\\Arrays\\ArrayOfWarning',
            'Warning'                                => '\\Ntvspa\\Big\\Booking\\Structs\\Warning',
            'ExceptionInfo'                          => '\\Ntvspa\\Big\\Booking\\Structs\\ExceptionInfo',
            'ArrayOfAdditionalMessage'               => '\\Ntvspa\\Big\\Booking\\Arrays\\ArrayOfAdditionalMessage',
            'AdditionalMessage'                      => '\\Ntvspa\\Big\\Booking\\Structs\\AdditionalMessage',
            'ServiceFault'                           => '\\Ntvspa\\Big\\Booking\\Structs\\ServiceFault',
            'ArrayOfJourneyDateMarket'               => '\\Ntvspa\\Big\\Booking\\Arrays\\ArrayOfJourneyDateMarket',
            'JourneyDateMarket'                      => '\\Ntvspa\\Big\\Booking\\Structs\\JourneyDateMarket',
            'ArrayOfSegment'                         => '\\Ntvspa\\Big\\Booking\\Arrays\\ArrayOfSegment',
            'Segment'                                => '\\Ntvspa\\Big\\Booking\\Structs\\Segment',
            'ArrayOfFare'                            => '\\Ntvspa\\Big\\Booking\\Arrays\\ArrayOfFare',
            'Fare'                                   => '\\Ntvspa\\Big\\Booking\\Structs\\Fare',
            'ArrayOfPaxFare'                         => '\\Ntvspa\\Big\\Booking\\Arrays\\ArrayOfPaxFare',
            'PaxFare'                                => '\\Ntvspa\\Big\\Booking\\Structs\\PaxFare',
            'FarePolicy'                             => '\\Ntvspa\\Big\\Booking\\Structs\\FarePolicy',
            'FareBasisRestrictionRules'              => '\\Ntvspa\\Big\\Booking\\Structs\\FareBasisRestrictionRules',
            'ArrayOfFareBasisGroup'                  => '\\Ntvspa\\Big\\Booking\\Arrays\\ArrayOfFareBasisGroup',
            'FareBasisGroup'                         => '\\Ntvspa\\Big\\Booking\\Structs\\FareBasisGroup',
            'ArrayOfFareLockInfoChoiceData'          => '\\Ntvspa\\Big\\Booking\\Arrays\\ArrayOfFareLockInfoChoiceData',
            'FareLockInfoChoiceData'                 => '\\Ntvspa\\Big\\Booking\\Structs\\FareLockInfoChoiceData',
            'ArrayOfstring'                          => '\\Ntvspa\\Big\\Booking\\Arrays\\ArrayOfstring',
            'ArrayOfshort'                           => '\\Ntvspa\\Big\\Booking\\Arrays\\ArrayOfshort',
            'HoldBookingRequest'                     => '\\Ntvspa\\Big\\Booking\\Structs\\HoldBookingRequest',
            'HoldBookingResponse'                    => '\\Ntvspa\\Big\\Booking\\Structs\\HoldBookingResponse',
            'LoungeData'                             => '\\Ntvspa\\Big\\Booking\\Structs\\LoungeData',
            'ArrayOfLounge'                          => '\\Ntvspa\\Big\\Booking\\Arrays\\ArrayOfLounge',
            'Lounge'                                 => '\\Ntvspa\\Big\\Booking\\Structs\\Lounge',
            'UpgradeData'                            => '\\Ntvspa\\Big\\Booking\\Structs\\UpgradeData',
            'ArrayOfSegmentUpgrade'                  => '\\Ntvspa\\Big\\Booking\\Arrays\\ArrayOfSegmentUpgrade',
            'SegmentUpgrade'                         => '\\Ntvspa\\Big\\Booking\\Structs\\SegmentUpgrade',
            'PetData'                                => '\\Ntvspa\\Big\\Booking\\Structs\\PetData',
            'ArrayOfPet'                             => '\\Ntvspa\\Big\\Booking\\Arrays\\ArrayOfPet',
            'Pet'                                    => '\\Ntvspa\\Big\\Booking\\Structs\\Pet',
            'ErasabilityOption'                      => '\\Ntvspa\\Big\\Booking\\Structs\\ErasabilityOption',
            'Booking'                                => '\\Ntvspa\\Big\\Booking\\Structs\\Booking',
            'ArrayOfAvailableUpgrade'                => '\\Ntvspa\\Big\\Booking\\Arrays\\ArrayOfAvailableUpgrade',
            'AvailableUpgrade'                       => '\\Ntvspa\\Big\\Booking\\Structs\\AvailableUpgrade',
            'ArrayOfPayment'                         => '\\Ntvspa\\Big\\Booking\\Arrays\\ArrayOfPayment',
            'Payment'                                => '\\Ntvspa\\Big\\Booking\\Structs\\Payment',
            'ArrayOfNullableOfshort'                 => '\\Ntvspa\\Big\\Booking\\Arrays\\ArrayOfNullableOfshort',
            'ArrayOfBookingComment'                  => '\\Ntvspa\\Big\\Booking\\Arrays\\ArrayOfBookingComment',
            'BookingComment'                         => '\\Ntvspa\\Big\\Booking\\Structs\\BookingComment',
            'ThreeDSecureAuthRes'                    => '\\Ntvspa\\Big\\Booking\\Structs\\ThreeDSecureAuthRes',
            'ManagePaymentRequest'                   => '\\Ntvspa\\Big\\Booking\\Structs\\ManagePaymentRequest',
            'ManagePaymentResponse'                  => '\\Ntvspa\\Big\\Booking\\Structs\\ManagePaymentResponse',
            'PayPalPayment'                          => '\\Ntvspa\\Big\\Booking\\Structs\\PayPalPayment',
            'ThreeDSecureAuthReq'                    => '\\Ntvspa\\Big\\Booking\\Structs\\ThreeDSecureAuthReq',
            'ThreeDSecureAcsResponse'                => '\\Ntvspa\\Big\\Booking\\Structs\\ThreeDSecureAcsResponse',
            'AmazonPayPayment'                       => '\\Ntvspa\\Big\\Booking\\Structs\\AmazonPayPayment',
            'FinalizeBookingRequest'                 => '\\Ntvspa\\Big\\Booking\\Structs\\FinalizeBookingRequest',
            'FinalizeBookingResponse'                => '\\Ntvspa\\Big\\Booking\\Structs\\FinalizeBookingResponse',
            'GetBookingRequest'                      => '\\Ntvspa\\Big\\Booking\\Structs\\GetBookingRequest',
            'GetBookingResponse'                     => '\\Ntvspa\\Big\\Booking\\Structs\\GetBookingResponse',
            'GetBookingFromStateRequest'             => '\\Ntvspa\\Big\\Booking\\Structs\\GetBookingFromStateRequest',
            'GetBookingFromStateResponse'            => '\\Ntvspa\\Big\\Booking\\Structs\\GetBookingFromStateResponse',
            'DeleteJourneyRequest'                   => '\\Ntvspa\\Big\\Booking\\Structs\\DeleteJourneyRequest',
            'DeleteJourneyResponse'                  => '\\Ntvspa\\Big\\Booking\\Structs\\DeleteJourneyResponse',
            'ManageSSRRequest'                       => '\\Ntvspa\\Big\\Booking\\Structs\\ManageSSRRequest',
            'ManageSSRResponse'                      => '\\Ntvspa\\Big\\Booking\\Structs\\ManageSSRResponse',
            'GetPDFTicketRequest'                    => '\\Ntvspa\\Big\\Booking\\Structs\\GetPDFTicketRequest',
            'GetPDFTicketResponse'                   => '\\Ntvspa\\Big\\Booking\\Structs\\GetPDFTicketResponse',
            'FindBookingRequest'                     => '\\Ntvspa\\Big\\Booking\\Structs\\FindBookingRequest',
            'FindBookingResponse'                    => '\\Ntvspa\\Big\\Booking\\Structs\\FindBookingResponse',
            'Customer'                               => '\\Ntvspa\\Big\\Booking\\Structs\\Customer',
            'ArrayOfBooking'                         => '\\Ntvspa\\Big\\Booking\\Arrays\\ArrayOfBooking',
            'GetGRMContentRequest'                   => '\\Ntvspa\\Big\\Booking\\Structs\\GetGRMContentRequest',
            'GetGRMContentResponse'                  => '\\Ntvspa\\Big\\Booking\\Structs\\GetGRMContentResponse',
            'GetBestPriceForJourneyRequest'          => '\\Ntvspa\\Big\\Booking\\Structs\\GetBestPriceForJourneyRequest',
            'GetBestPriceForJourneyResponse'         => '\\Ntvspa\\Big\\Booking\\Structs\\GetBestPriceForJourneyResponse',
            'AddBookingCommentsRequest'              => '\\Ntvspa\\Big\\Booking\\Structs\\AddBookingCommentsRequest',
            'AddBookingCommentsResponse'             => '\\Ntvspa\\Big\\Booking\\Structs\\AddBookingCommentsResponse',
            'ManageFeeRequest'                       => '\\Ntvspa\\Big\\Booking\\Structs\\ManageFeeRequest',
            'ManageFeeResponse'                      => '\\Ntvspa\\Big\\Booking\\Structs\\ManageFeeResponse',
            'AddData'                                => '\\Ntvspa\\Big\\Booking\\Structs\\AddData',
            'DeleteData'                             => '\\Ntvspa\\Big\\Booking\\Structs\\DeleteData',
            'OverrideFeeRequest'                     => '\\Ntvspa\\Big\\Booking\\Structs\\OverrideFeeRequest',
            'OverrideFeeResponse'                    => '\\Ntvspa\\Big\\Booking\\Structs\\OverrideFeeResponse',
            'MoveRequest'                            => '\\Ntvspa\\Big\\Booking\\Structs\\MoveRequest',
            'MoveResponse'                           => '\\Ntvspa\\Big\\Booking\\Structs\\MoveResponse',
            'DivideSplitRequest'                     => '\\Ntvspa\\Big\\Booking\\Structs\\DivideSplitRequest',
            'DivideSplitResponse'                    => '\\Ntvspa\\Big\\Booking\\Structs\\DivideSplitResponse',
            'AssignSeatRequest'                      => '\\Ntvspa\\Big\\Booking\\Structs\\AssignSeatRequest',
            'AssignSeatResponse'                     => '\\Ntvspa\\Big\\Booking\\Structs\\AssignSeatResponse',
            'StartPaypalTransactionRequest'          => '\\Ntvspa\\Big\\Booking\\Structs\\StartPaypalTransactionRequest',
            'StartPaypalTransactionResponse'         => '\\Ntvspa\\Big\\Booking\\Structs\\StartPaypalTransactionResponse',
            'ExternalPaymentFinalizeBookingRequest'  => '\\Ntvspa\\Big\\Booking\\Structs\\ExternalPaymentFinalizeBookingRequest',
            'ExternalPaymentFinalizeBookingResponse' => '\\Ntvspa\\Big\\Booking\\Structs\\ExternalPaymentFinalizeBookingResponse',
            'GetSeatAvailabilityRequest'             => '\\Ntvspa\\Big\\Booking\\Structs\\GetSeatAvailabilityRequest',
            'GetSeatAvailabilityResponse'            => '\\Ntvspa\\Big\\Booking\\Structs\\GetSeatAvailabilityResponse',
            'Equipment'                              => '\\Ntvspa\\Big\\Booking\\Structs\\Equipment',
            'ArrayOfCompartment'                     => '\\Ntvspa\\Big\\Booking\\Arrays\\ArrayOfCompartment',
            'Compartment'                            => '\\Ntvspa\\Big\\Booking\\Structs\\Compartment',
            'ArrayOfSeat'                            => '\\Ntvspa\\Big\\Booking\\Arrays\\ArrayOfSeat',
            'Seat'                                   => '\\Ntvspa\\Big\\Booking\\Structs\\Seat',
            'ArrayOfEquipmentProperty'               => '\\Ntvspa\\Big\\Booking\\Arrays\\ArrayOfEquipmentProperty',
            'EquipmentProperty'                      => '\\Ntvspa\\Big\\Booking\\Structs\\EquipmentProperty',
            'ArrayOfSeatGroupPassengerFee'           => '\\Ntvspa\\Big\\Booking\\Arrays\\ArrayOfSeatGroupPassengerFee',
            'SeatGroupPassengerFee'                  => '\\Ntvspa\\Big\\Booking\\Structs\\SeatGroupPassengerFee',
            'GetLowFareTripRequest'                  => '\\Ntvspa\\Big\\Booking\\Structs\\GetLowFareTripRequest',
            'GetLowFareTripResponse'                 => '\\Ntvspa\\Big\\Booking\\Structs\\GetLowFareTripResponse',
            'GetLowFareTripData'                     => '\\Ntvspa\\Big\\Booking\\Structs\\GetLowFareTripData',
            'ArrayOfJourneyMarket'                   => '\\Ntvspa\\Big\\Booking\\Arrays\\ArrayOfJourneyMarket',
            'JourneyMarket'                          => '\\Ntvspa\\Big\\Booking\\Structs\\JourneyMarket',
            'ArrayOfJourneyLowFare'                  => '\\Ntvspa\\Big\\Booking\\Arrays\\ArrayOfJourneyLowFare',
            'JourneyLowFare'                         => '\\Ntvspa\\Big\\Booking\\Structs\\JourneyLowFare',
            'ExportBookingInfoRequest'               => '\\Ntvspa\\Big\\Booking\\Structs\\ExportBookingInfoRequest',
            'ExportBookingInfoResponse'              => '\\Ntvspa\\Big\\Booking\\Structs\\ExportBookingInfoResponse',
            'BookingNote'                            => '\\Ntvspa\\Big\\Booking\\Structs\\BookingNote',
            'CancelInProcessPaymentRequest'          => '\\Ntvspa\\Big\\Booking\\Structs\\CancelInProcessPaymentRequest',
            'CancelInProcessPaymentResponse'         => '\\Ntvspa\\Big\\Booking\\Structs\\CancelInProcessPaymentResponse',
            'FindBookingInternalRequest'             => '\\Ntvspa\\Big\\Booking\\Structs\\FindBookingInternalRequest',
            'FindBookingInternalResponse'            => '\\Ntvspa\\Big\\Booking\\Structs\\FindBookingInternalResponse',
            'GetUpgradeAvailabilityRequest'          => '\\Ntvspa\\Big\\Booking\\Structs\\GetUpgradeAvailabilityRequest',
            'GetUpgradeAvailabilityResponse'         => '\\Ntvspa\\Big\\Booking\\Structs\\GetUpgradeAvailabilityResponse',
            'UpgradeRequest'                         => '\\Ntvspa\\Big\\Booking\\Structs\\UpgradeRequest',
            'UpgradeResponse'                        => '\\Ntvspa\\Big\\Booking\\Structs\\UpgradeResponse',
            'ClearSeatsPreferencesRequest'           => '\\Ntvspa\\Big\\Booking\\Structs\\ClearSeatsPreferencesRequest',
            'ClearSeatsPreferencesResponse'          => '\\Ntvspa\\Big\\Booking\\Structs\\ClearSeatsPreferencesResponse',
            'UpdatePassengersRequest'                => '\\Ntvspa\\Big\\Booking\\Structs\\UpdatePassengersRequest',
            'UpdatePassengersResponse'               => '\\Ntvspa\\Big\\Booking\\Structs\\UpdatePassengersResponse',
            'ManageUpgradeRequest'                   => '\\Ntvspa\\Big\\Booking\\Structs\\ManageUpgradeRequest',
            'ManageUpgradeResponse'                  => '\\Ntvspa\\Big\\Booking\\Structs\\ManageUpgradeResponse',
        ];
    }
}
